version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - loan_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: loan_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loan_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: loan_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loan_system
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: loan_user
      MYSQL_PASSWORD: loan_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loan_network

  redis:
    image: redis:alpine
    container_name: loan_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - loan_network

  mailhog:
    image: mailhog/mailhog
    container_name: loan_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - loan_network

volumes:
  mysql_data:

networks:
  loan_network:
    driver: bridge